server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hlizama/spring-cloud-config.git
          
          # If you are using ssh key to connect private git repository use following configs
          #
          # uri: git@{gitserver}.com:/repourl
          # ignoreLocalSshSettings: true
          # hostKey: someHostKey
          # hostKeyAlgorithm: ssh-rsa
          # privateKey: 
          #           -----BEGIN RSA PRIVATE KEY-----
          #           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          #           your SSH Key in ~/.ssh/id_rsa
          #           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          #           -----END RSA PRIVATE KEY-----