server:
  port: 8040
spring:
  cloud:
    config:
      server:
        git:
          default-label: develop
          uri: https://github.com/wpacpac/bootcamp2022Microservicios.git
          search-paths: spring-cloud-config
  application:
    name: config-service